language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../src

script:

      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#      - mvn clean verify sonar:sonar
#      - cd ../docker/dev
#      - docker-compose stop
#      - docker-compose rm -f
#      - docker-compose up -d
#      - docker ps -a
#      - cd ../../src

addons:
  sonarcloud:
    organization: "fabien49"
    token:
      secure: 93b7e96bb4a94541d6f1f117d7e9dd8f2a863e4e # encrypted value of your token

      script:
        # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
        - mvn clean verify sonar:sonar -Pcoverage

      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.sonar/cache'




